Controllers/CarController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using roadlovers.Models;
using roadlovers.Persistence;
using roadlovers.Repositories;

namespace roadlovers.Controllers
{
    public class CarController : Controller
    {
        private ICarRepository _repo;

        private IManufacturerRepository _repoManufacturer;

        private IVehicleTypeRepository _repoVehicleClasses;

        private IColorRepository _repoColor;

        private IVehicleColorRepository _repoVehCol;

        public CarController(ICarRepository repo, IManufacturerRepository repoManufacturer, IVehicleTypeRepository repoVehicleClasses, IColorRepository repoColor, IVehicleColorRepository repoVehCol)
        {
            _repo = repo;
            _repoManufacturer = repoManufacturer;
            _repoVehicleClasses = repoVehicleClasses;
            _repoColor = repoColor;
            _repoVehCol = repoVehCol;
        }

        [HttpPost]
        public IActionResult Color(VehicleColor vehicleColor)
        {
            _repoVehCol.Store(vehicleColor);
            _repoVehCol.Commit();

            return RedirectToAction("Colors", new { id = vehicleColor.CarId });
        }

        [HttpGet]
        public IActionResult Colors(int id)
        {
            // All colors
            IList<Color> allColors = _repoColor.FindAll();
            // Vehicle colors
            IList<Color> vehicleColors = _repoColor.FindAllByCarId(id);

            var filtered = allColors.Where(c => !vehicleColors.Any(s => s.ColorId == c.ColorId));

            ViewBag.selectColors = new SelectList(filtered, "ColorId", "Name");
            ViewBag.colors = vehicleColors;

            VehicleColor vehicleColor = new VehicleColor()
            {
                Car = _repo.FindById(id)
            };

            return View(vehicleColor);
        }


        [HttpGet]
        public IActionResult Index(int? year, int? manufacturerId, int? vehicleTypeId)
        {
            IList<Car> cars = _repo.FindBy(s => 
                (s.Year == year || year == null) && 
                (s.ManufacturerId == manufacturerId || manufacturerId == null) &&
                (s.VehicleTypeId == vehicleTypeId || vehicleTypeId == null) 
            );

            LoadManufacturers();
            LoadClasses();

            return View(cars);

        }

        [HttpPost]
        public IActionResult Store(Car car)
        {
            _repo.Store(car);
            _repo.Commit();

            @TempData["msg"] = $"Veículo {car.Manufacturer} {car.Model} cadastrado com sucesso";

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Store()
        {
            LoadManufacturers();
            LoadClasses();
            return View();
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            LoadManufacturers();
            LoadClasses();
            return View(_repo.FindById(id));
        }

        [HttpPost]
        public IActionResult Edit(Car car)
        {
            _repo.Update(car);
            _repo.Commit();

            @TempData["msg"] = $"Veículo atualizado com sucesso";

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Remove(int id)
        {
            _repo.Destroy(id);
            _repo.Commit();

            @TempData["msg"] = $"Veículo removido com sucesso";

            return RedirectToAction("Index");
        }

        private void LoadManufacturers()
        {
            IList<Manufacturer> manufacturers = _repoManufacturer.FindAll();

            ViewBag.manufacturers = new SelectList(manufacturers, "ManufacturerId", "Name");
        }

        private void LoadClasses()
        {
            IList<VehicleType> vehicleTypes = _repoVehicleClasses.FindAll();

            ViewBag.classes = new SelectList(vehicleTypes, "VehicleTypeId", "Description");
        }
    }
}

Controllers/ColorController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using roadlovers.Models;
using roadlovers.Repositories;

namespace roadlovers.Controllers
{
    public class ColorController : Controller
    {
        private readonly ILogger<ColorController> _logger;

        private IColorRepository _repo;

        public ColorController(ILogger<ColorController> logger, IColorRepository repo)
        {
            _logger = logger;
            _repo = repo;
        }

        public IActionResult Index()
        {
            ViewBag.colors = _repo.FindAll();
            return View();
        }

        [HttpPost]
        public IActionResult Store(Color color)
        {
            _repo.Store(color);
            _repo.Commit();

            TempData["msg"] = "Cor registrada com sucesso";

            return RedirectToAction("Index");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Controllers/ManufacturerController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using roadlovers.Models;
using roadlovers.Repositories;

namespace roadlovers.Controllers
{
    public class ManufacturerController : Controller
    {
        private readonly ILogger<ManufacturerController> _logger;

        private IManufacturerRepository _repo;

        public ManufacturerController(ILogger<ManufacturerController> logger, IManufacturerRepository repo)
        {
            _logger = logger;
            _repo = repo;
        }

        public IActionResult Index()
        {
            ViewBag.manufacturers = _repo.FindAll();
            return View();
        }

        [HttpPost]
        public IActionResult Store(Manufacturer manufacturer)
        {
            _repo.Store(manufacturer);
            _repo.Commit();

            TempData["msg"] = "Fabricante cadastrada";

            return RedirectToAction("Index");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Controllers/VehicleTypeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using roadlovers.Models;
using roadlovers.Repositories;

namespace roadlovers.Controllers
{
    public class VehicleTypeController : Controller
    {
        private readonly ILogger<VehicleTypeController> _logger;

        private IVehicleTypeRepository _repo;

        public VehicleTypeController(ILogger<VehicleTypeController> logger, IVehicleTypeRepository repo)
        {
            _logger = logger;
            _repo = repo;
        }

        public IActionResult Index()
        {
            ViewBag.classes = _repo.FindAll();

            return View();
        }

        [HttpPost]
        public IActionResult Store(VehicleType type)
        {
            _repo.Store(type);
            _repo.Commit();

            TempData["msg"] = "Classe cadastrada com sucesso";

            return RedirectToAction("Index");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View("Error!");
        }
    }
}

Views/Shared/_Layout.cshtml
@{
    string SiteName = "RoadLovers";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] | @SiteName</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@SiteName</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Principal</a>
                        </li>
                        <li class="nav-item collapse">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacidade</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Car" asp-action="Index">Veículos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Manufacturer" asp-action="Index">Fabricantes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="VehicleType" asp-action="Index">Classes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Color" asp-action="Index">Cores</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - @SiteName - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacidade</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>